apiVersion: v1
version: 1.0.0
appVersion: 1.0.0
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/awsdevopsssp/flux-helm/
maintainers:
- email: ssp@gmail.com
  name: ssp
sources:
- https://github.com/awsdevopsssp/flux-helm/

